### ISSUE TITLE
erreur in executing command : rake test_install and when enable the service

### ISSUE THREAD

**Issue by fkihAZAIEZ** [Support-pl/ione#145]
hello,
after installing ione and all is ok, when i exute the command "rake test_install" i get this erreur :Can't connect to database, got: Too many matches for path expression There are 2 nodes matching DB/BACKEND
![trouble 1](https://user-images.githubusercontent.com/82452774/135296605-34cb275a-518c-4d1f-912f-2f1c6e6d8e5a.PNG)
and when i would like to start the ione service, it said to me not found 
![trouble 2](https://user-images.githubusercontent.com/82452774/135297149-f80099b1-a24e-4570-9031-695695090633.PNG)
what i suppose to do ?

**Comment by fkihAZAIEZ** [comment]
@slntopp can you help me please ?

**Comment by slntopp** [comment]
Hi, do you have logs during install? Looks ione install wasn't completed

regarding first screenshot: you should check your oned.conf, you might have had uncommented some DB section, so there are two. It must be only one

**Comment by fkihAZAIEZ** [comment]
Hello @slntopp ,i installed the ione in the same machine with opennebula front-end ,is that a problem ?
also i think that i installed correctly, look at this screenshot :
![make install done](https://user-images.githubusercontent.com/82452774/135723848-2a86c281-9db4-4aef-ac3f-d7c6c3f2f64d.PNG)
and in the second screenshot my oned.conf (DB part)
![Ubuntu18 04(opennebula 6) -2021-10-02-16-59-56](https://user-images.githubusercontent.com/82452774/135723941-e5acb15a-a559-4e06-95ab-733d0fe3c557.png)
When i comment the 2 lines :
DB = [ BACKEND = "sqlite",
       TIMEOUT = 2500 ]
 i got this error: 
![rake](https://user-images.githubusercontent.com/82452774/135724122-7158b93f-14bf-4b96-a518-418a4e239f38.PNG)

**Comment by slntopp** [comment]
Hi
Regarding ione.service, check if that file exists at `/usr/lib/systemd/system`. If it's not there, just copy it from `sys` dir in ione repo.

About the DB, ione doesn't support sqlite out of the box, you should consider using MySQL or PostgreSQL

**Comment by fkihAZAIEZ** [comment]
Hi @slntopp ,
I allready have this file in the diractory systemd
![image](https://user-images.githubusercontent.com/82452774/135733921-2f2aa2cc-67be-4562-ab2a-15fe5043ed53.png)
Concerning the database, also i allready use MySQL when i install the OpenNebula front-end
![image](https://user-images.githubusercontent.com/82452774/135734030-21326b6f-4941-4037-b587-b075c5c2968a.png)
what should i do ?

**Comment by slntopp** [comment]
Sorry, yes, you just need to comment DB Section where backend="sqlite"

With systemd, try 
```shell
systemctl daemon-reload
# and then
systemctl start ione
```

**Comment by slntopp** [comment]
Systemd issue can be caused because you use Ubuntu.
Unfortunately installer and IONe itself wasn't properly tested on Ubuntu yet. In case my previous suggestion won't work and you find other way to resolve this issue, it would be very helpful if you log it here. Thanks

**Comment by fkihAZAIEZ** [comment]
i tried what you said for me but the same thing 
![image](https://user-images.githubusercontent.com/82452774/135734245-f0b31092-e668-497a-a9d0-19949b084f37.png)
I encountered several problems when installing the ione : i changed "yum" to "apt" in  ione/rake/install_deps.rake, also i installed many services manuelly but finally no result.
So, can i create a new VM RHEL 8 and i'll install only the ione, is that work ?

**Comment by slntopp** [comment]
Installing ione on CentOS/RHEL is quite recommended, so if you can and want to, you should try.

But actually, checking systemd docs for Ubuntu could be more useful, because:
 - Rest(main part) of IONe seems to be installed
 - Much recommended to run IONe on the same host(otherwise installer is no use for setting up hooks etc)

Also I could suggest you to try using Dockerized IONe.

**Comment by fkihAZAIEZ** [comment]
Ok
thank you for your help .
