### ISSUE TITLE
rake install

### ISSUE THREAD

**Issue by holaloc** [Support-pl/ione#151]
hi,

I tried to install it on Centos8 but no success 

======
rake aborted!
LoadError: cannot load such file -- opennebula
rake/set_hooks.rake:1:in `<top (required)>'
/home/open/ione/Rakefile:60:in `load'
/home/open/ione/Rakefile:60:in `<top (required)>'
(See full trace by running task with --trace)
======

OpenNebula | 6.1
Ruby | 2.5.5 
Node | 16

**Comment by slntopp** [comment]
hi,
make sure you have opennebula in `gem list`
