### ISSUE TITLE
rake install failed

### ISSUE THREAD

**Issue by Login-out** [Support-pl/ione#209]
Install iONe failed when I  complied with "rake install ". 

The log as follow:
[root@iONe ione]# cat /etc/redhat-release 
CentOS Stream release 8
[root@iONe ione]# pwd
/var/lib/one/ione
[root@iONe ione]# 
[root@iONe ione]# rake install
rake aborted!
LoadError: cannot load such file -- opennebula
rake/set_hooks.rake:1:in `<top (required)>'
/var/lib/one/ione/Rakefile:60:in `load'
/var/lib/one/ione/Rakefile:60:in `<top (required)>'
/usr/share/gems/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)

**Comment by slntopp** [comment]
Hi, one should be using Docker image now

**Comment by Login-out** [comment]
I try to use docker,but login failed. It notice “Endpoint used for login: http://localhost:8009”
When I change the localhost to ione.domain.com, Its still exists

this is my docker-compose.yml
[root@vcloud ione]# vim docker-compose.yml
[root@vcloud ione]# 
[root@vcloud ione]# 
[root@vcloud ione]# docker-compose up -d
[+] Running 2/2
 ⠿ Container ione-ione-admin-1  Started                                                                                                                            0.3s
 ⠿ Container ione-ione-1        Started                                                                                                                            0.3s
[root@vcloud ione]# cat docker-compose.yml
version: '3.7'
services:
  ione:
    image: ghcr.io/support-pl/ione:latest
    network_mode: host
    environment:
      ALPINE: "true"
      IONE_LOCATION: /ione
      ONE_LOCATION: /ione/sys
      LOG_LOCATION: /log
      ONE_CREDENTIALS: "oneadmin:oneadmin"
      DB_BACKEND: mysql
      DB_HOST: 10.8.2.2
      DB_USER: ione
      DB_PASSWORD: ione
      DB_DATABASE: opennebula
      ONE_ENDPOINT: "http://localhost:2633/RPC2"
    volumes:
      - ./sys:/ione/sys
      - /var/log/one:/log
  ione-admin:
    image: ghcr.io/support-pl/ione-admin:latest
    network_mode: host
    environment: 
      VUE_APP_IONE_API_BASE_URL: http://localhost:8009
      PORT: 5000

**Comment by Login-out** [comment]
Yes, I access IONe Admin UI，http://10.8.2.2:5000/#/login
![image](https://user-images.githubusercontent.com/16233886/163083912-5ae93fcc-f2c4-4bce-aca4-d268d2fbf192.png)

**Comment by slntopp** [comment]
First you should change VUE_APP_IONE_API_BASE_URL to the accessible one, which is I suppose http://10.8.2.2:8009
But Second, certificates needed one way or another, you can see DevTools Console for exact error context, your browser won't let you access anything if API URL is not secure(https://)

**Comment by Login-out** [comment]
Do you know which service is listening on port 8009 ？
![image](https://user-images.githubusercontent.com/16233886/163087038-0762395d-ec6b-4235-bdf3-b733fab6a655.png)

**Comment by Login-out** [comment]
All services are in this server（10.8.2.2）

**Comment by slntopp** [comment]
Defaults are: IONe API at 8009, Admin UI at 5000

**Comment by Login-out** [comment]
I  have not config ssl certification
I am confused why there is no service listening on port 8009, how can I start this service.

**Comment by Login-out** [comment]
I have finish it !!! 

1.need to copy ione.conf to ./sys dir 
2.8009 just listen in 127.0.0.1, I use nginx proxy 10.8.2.2:8010 to 127.0.0.1:8009 
3.change VUE_APP_IONE_API_BASE_URL=http://10.8.2.2:8010 
4.docker-compose up -d

DONE !!!!
Thanks a lot

**Comment by slntopp** [comment]
Glad it worked
